### PR TITLE
Update `:jsx` to `2.8.0`.

### PR DESCRIPTION
**Pull request by izaakschroeder**
There have been no incompatible changes between versions, (as documented here https://github.com/talentdeficit/jsx/blob/develop/CHANGES.md), so upgrading seems like a sane thing to do. This is also required for using `exjsx` in applications that use the latest version of `ex_aws` because it requires `~> 2.8.0`.

### CODE REVIEW

**Comment by talentdeficit** [comment]
thanks

**Comment by talentdeficit** [comment]
i bumped the version to 3.2.1 and published to hex

**Comment by izaakschroeder** [comment]
Thank you! Lemme know when the new version is published 😄

**Comment by izaakschroeder** [comment]
Oh. Beat me to it. Awesome! Thanks again!

**Pull request merged**
